---
- name: Update packages
  ansible.builtin.apt:
    upgrade: dist
    update_cache: yes
  notify: reboot
  tags: apt_update

- name: Install fail2ban
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - fail2ban
    - ufw # for Debian
    - gnupg # for Debian

- name: Setup UFW
  ansible.builtin.include_tasks: ufw.yml

- name: Create swap file
  ansible.builtin.include_tasks: create_swap.yml
  when: ansible_swaptotal_mb < 2047

- name: Update locale
  community.general.locale_gen:
    name: "{{ locale }}"
    state: present
  tags: locale

- name: Max. 50 Mb total for files in /var/log/journal/
  ansible.builtin.lineinfile:
    path: /etc/systemd/journald.conf
    regexp: "SystemMaxUse"
    line: SystemMaxUse=50M
    state: present

# ###################################
#    Harden /etc/ssh/sshd_config

# Ubuntu 20+, Debian 11+
# https://linuxliteracy.com/new-way-to-manage-ssh-options-in-ubuntu-20-04/
- name: Override settings in /etc/ssh/sshd_config
  ansible.builtin.copy:
    dest: /etc/ssh/sshd_config.d/10-hardening.conf
    content: |
      PermitRootLogin yes
      PasswordAuthentication no
      LoginGraceTime 15
      X11Forwarding no
      PubkeyAuthentication yes
      ClientAliveInterval 600
    mode: 0600
    validate: "/usr/sbin/sshd -t -f %s"
  notify: sshd_reload
  register: sshd_config
  when: >
    ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 20 or
    ansible_distribution == "Debian" and ansible_distribution_major_version|int >= 11

# Not any of the above
- block:
  - name: Edit settings in /etc/ssh/sshd_config
    ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
      state: present
      validate: "/usr/sbin/sshd -T -f %s"
    with_items:
      - { regexp: '^#?PermitRootLogin', line: 'PermitRootLogin yes' }
      - { regexp: '^#?PasswordAuthentication yes', line: 'PasswordAuthentication no' }
      - { regexp: '^#?LoginGraceTime.+', line: 'LoginGraceTime 15' }
      - { regexp: '^X11Forwarding yes', line: 'X11Forwarding no' }
      - { regexp: '^#?PubkeyAuthentication.+', line: 'PubkeyAuthentication yes' }
      - { regexp: '^#?ClientAliveInterval.+', line: 'ClientAliveInterval 600' }
  when: sshd_config.skipped is defined and sshd_config.skipped

# ###################################
#          Misc. hardening
- name: Remove package whois
  ansible.builtin.apt:
    name: whois
    state: absent

# https://www.techrepublic.com/article/how-to-enable-secure-shared-memory-on-ubuntu-server/
- name: Secure shared memory
  ansible.builtin.lineinfile:
    path: /etc/fstab
    line: "none     /run/shm     tmpfs     defaults,ro     0     0"
    state: present
    validate: mount -a -T %s
